<?php
/**
 * AnnotationLabelsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Open Legal Data API
 *
 * With the Open Legal Data API you can access various data from the legal domain, e.g. law text or case files. The data may be used for semantic analysis or to create statistics. For more information visit our website. https://openlegaldata.io/
 *
 * OpenAPI spec version: v1
 * Contact: hello@openlegaldata.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AnnotationLabelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AnnotationLabelsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for annotationLabelsCreate
     *
     * .
     *
     */
    public function testAnnotationLabelsCreate()
    {
    }

    /**
     * Test case for annotationLabelsDelete
     *
     * .
     *
     */
    public function testAnnotationLabelsDelete()
    {
    }

    /**
     * Test case for annotationLabelsList
     *
     * .
     *
     */
    public function testAnnotationLabelsList()
    {
    }

    /**
     * Test case for annotationLabelsPartialUpdate
     *
     * .
     *
     */
    public function testAnnotationLabelsPartialUpdate()
    {
    }

    /**
     * Test case for annotationLabelsRead
     *
     * .
     *
     */
    public function testAnnotationLabelsRead()
    {
    }

    /**
     * Test case for annotationLabelsUpdate
     *
     * .
     *
     */
    public function testAnnotationLabelsUpdate()
    {
    }
}
